
services:

  frontend:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network

  backend:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABASE: food_system
      MYSQL_USER: deerhack
      MYSQL_PASSWORD: deerhackpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  reverse_proxy:
    image: haproxy
    ports:
      - "8001:8001"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
